image: $CI_REGISTRY/risking/build-image:master

build:
  stage: build
  script:
    - mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug ..
    - make
  artifacts:
    paths:
      - build/
    expire_in: 7 days

# run tests using the binary built
test:
  stage: test
  needs:
    - build
  script:
    - cd build
    - ctest -T test --verbose --no-compress-output --output-on-failure
  after_script:
    - python3 CMakeModules/CTest2JUnit.py build CMakeModules/CTest2JUnit.xsl > junit.xml
  artifacts:
    paths:
      - junit.xml
    reports:
      junit: junit.xml
    expire_in: 7 days

#run coverage
coverage:
  stage: deploy
  needs:
    - test
  script:
    - cmake -DCOVERAGE=ON -DCMAKE_BUILD_TYPE=Debug .
    - make all coverage
    - make all coverage_html
    - mv coverage_html coverage
    - chmod u+x utils/coverage_report.py
    - python3 utils/coverage_report.py
  artifacts:
    paths:
      - coverage/
    expire_in: 7 days
    reports:
      cobertura: coverage.xml
  coverage: '/COVERAGE PERCENTAGE: ([0-9.]+)/'

# Generate documentation (pdf)
doc_pdf:
  stage: deploy
  needs:
    - test
  before_script:
    - gem install asciidoctor asciidoctor-pdf asciidoctor-diagram --pre
  script:
    - asciidoctor-pdf -r asciidoctor-diagram doc/*.adoc
  artifacts:
    paths:
      - "doc/*.pdf"
    expire_in: 7 days

# Upload to Gitlab pages (html)
pages:
  stage: deploy
  needs:
    - test
  before_script:
    - gem install asciidoctor asciidoctor-pdf asciidoctor-diagram --pre
  script:
    - asciidoctor doc/*.adoc
    - mkdir -p public
    - mv doc/*.html public/
  artifacts:
    paths:
      - "public/"
    expire_in: 7 days
  only:
    refs:
      - develop
