# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: ubuntu:20.04

build:
  stage: build
  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - ln -fs /usr/share/zoneinfo/Europe/Paris /etc/localtime
    - apt update && apt -y install g++ make autoconf cmake libboost-all-dev
  script:
    - mkdir build && cd build
    - cmake ..
    - make
  artifacts:
    paths:
        - build/
    expire_in: 7 days
  
# run tests using the binary built
test:
  stage: test
  before_script:
    - apt update && apt -y install make cmake
  dependencies:
    - build
  script:
    - cd build
    - make test

#run coverage
#gcov:
#  stage: deploy
#  before_script:
#    - apt-get -qq update && apt-get -qq install -y make autoconf gcovr ggcov lcov
#  script:
#    - make clean && make GCOV=1 test
#    - ./tests.sh
#    - gcovr -s -f src/
#  coverage: '/lines: \d+\.\d+/'

# generate documentation
doc:
  stage: deploy
  before_script:
    - apt update && apt -y install gcc make autoconf doxygen ruby
    - gem install asciidoctor asciidoctor-pdf --pre
  script:
    - make doc
    - asciidoctor-pdf doc/*.adoc
  artifacts:
    paths:
      - "doc/*.pdf"
    expire_in: 7 days
